import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Experience", description: "DP’s professional experience at Visys Cloud Technologies and Intech Additive Solutions, spanning full-stack AI products and embedded systems." };

const roles = [
  { company: "Visys Cloud Technologies", city: "Hyderabad, India", dates: "April 2025 — May 2026", role: "Software Associate", focus: "Full-Stack & AI Product Developer", intro: "Connecting the entire product, from the first client conversation to the interface, API, and database behind it.", details: "Worked on full-stack and AI product development, with a focus on making recruitment workflows easier to manage. Combined hands-on development with team leadership and client communication.", contributions: ["Built an AI-powered applicant tracking system using Next.js and Python.", "Developed resume parsing, candidate ranking, and resume–job description matching workflows.", "Designed REST APIs with FastAPI and PostgreSQL, delivering features across frontend, backend, and database layers.", "Integrated email services for candidate communication.", "Led a three-person development team and served as the primary connection between the client and development team."], stack: ["Python", "Next.js", "FastAPI", "PostgreSQL", "GenAI"], signal: "3-person", signalLabel: "Development team led", project: true },
  { company: "Intech Additive Solutions", city: "Bengaluru, India", dates: "November 2023 — October 2024", role: "Software Engineer", focus: "Embedded Systems", intro: "Building software with a physical consequence. Where precision in code meets precision in metal.", details: "Developed software for embedded metal 3D printing systems, working at the intersection of software, mechanical engineering, and hardware.", contributions: ["Developed C++ backend modules for embedded metal 3D printing systems.", "Worked on laser control, power delivery, and hardware workflow orchestration.", "Developed laser trajectory and path-planning algorithms.", "Built frontend configuration tooling.", "Collaborated with mechanical and hardware teams on system performance."], stack: ["C++", "Embedded systems", "Path planning", "Hardware integration"], signal: "Code → motion", signalLabel: "Connecting software and physical systems", project: false },
];

export default function Experience() {
  return <div className="shell"><section className="page-intro"><p className="eyebrow">EXPERIENCE / WORK THAT SHAPED MY CRAFT</p><h1>Built in the real world.<br/><span className="orange">Across the whole stack.</span></h1><p className="page-lede">From embedded metal 3D printing systems to AI-powered web applications. A shared focus on turning complex requirements into working software.</p></section>
    {roles.map((job,i)=><article className="role-section reveal" key={job.company}><aside className="role-aside"><p className="eyebrow">0{i+1} / PROFESSIONAL EXPERIENCE</p><p className="role-dates">{job.dates}</p><p className="muted">{job.city}</p><div className="role-signal"><strong>{job.signal}</strong><span>{job.signalLabel}</span></div></aside><div className="role-body"><h2>{job.company}</h2><p className="role-title">{job.role} <span>— {job.focus}</span></p><h3>{job.intro}</h3><p>{job.details}</p><h4 className="mono">CONTRIBUTIONS & RESPONSIBILITIES</h4><ul className="contribution-list">{job.contributions.map(item=><li key={item}>{item}</li>)}</ul><div className="tags">{job.stack.map(skill=><span key={skill}>{skill}</span>)}</div>{job.project && <Link href="/projects#vcruitai" className="text-link">Explore the VcruitAI case study <span aria-hidden="true">↗</span></Link>}</div></article>)}
    <section className="inline-cta"><div><p className="eyebrow">THE NEXT CONVERSATION</p><h2>Have a role or a product in mind?</h2></div><Link href="/contact" className="button button-primary">Let’s Connect <span aria-hidden="true">↗</span></Link></section>
  </div>;
}
